#!/bin/bash
#SBATCH -N 1
#SBATCH -p RM-shared
#SBATCH -t 72:00:00
#SBATCH --ntasks-per-node 64
#SBATCH -A ees240004p
#SBATCH --mail-type=ALL
#echo commands to stdout

source /jet/home/hkittner/miniforge3/bin/activate
conda activate /jet/home/hkittner/miniforge3/envs/metawrap-env

metawrap bin_refinement -o /ocean/projects/ees240004p/hkittner/bin_refinement_S4_04_L001only -t 64 -m 128 -A /ocean/projects/ees240004p/hkittner/initial_binning_S4_04_L001only/metabat2_bins/ -B /ocean/projects/ees240004p/hkittner/initial_binning_S4_04_L001only/maxbin2_bins/ -C /ocean/projects/ees240004p/hkittner/initial_binning_S4_04_L001only/concoct_bins/ -c 80 -x 5
