#!/bin/bash
#SBATCH -N 1
#SBATCH -p RM-shared
#SBATCH -t 5:00:00
#SBATCH --ntasks-per-node 64
#SBATCH -A deb190007p
#SBATCH --mail-type=ALL
#echo commands to stdout


module load Trimmomatic/0.39

for file1 in *_R1_001.fastq.gz
do
file2=${file1/_R1_001.fastq.gz/_R2_001.fastq.gz}
out=${file1%%_R1_001.fastq.gz}

trimmomatic PE -threads 64 -trimlog ${out}_trimlog1_file.txt ${file1} ${file2} ${out}_forward_paired_trim1.fastq.gz ${out}_forward_unpaired_trim1.fastq.gz ${out}_reverse_paired_trim1.fastq.gz ${out}_reverse_unpaired_trim1.fastq.gz ILLUMINACLIP:/ocean/projects/deb190007p/hkittner/adapters/adapters_davis_hiseq_8_2019.fa:2:40:15
done


#### trim 1 (above) is just the adapters, looks at the slurm file to see what % of files get removed from just the adapters

#### trim 2 (below) is about both the adapters and the quality scores, if the length is below 151 (aka adpaters/quality trimmed read) it will be removed.  This is very stringent and can be adjusted.

for file1 in *_forward_paired_trim1.fastq.gz
do
file2=${file1/forward/reverse}
out=${file1%%_forward_paired_trim1.fastq.gz}

trimmomatic PE -threads 64 -trimlog ${out}_trimlog2_file.txt ${file1} ${file2} ${out}_forward_paired_trim.fastq.gz ${out}_forward_unpaired_trim.fastq.gz ${out}_reverse_paired_trim.fastq.gz ${out}_reverse_unpaired_trim.fastq.gz LEADING:10 TRAILING:10 SLIDINGWINDOW:4:25 MINLEN:140
done

module remove Trimmomatic/0.39

module load FastQC/0.11.9

for file1 in *_forward_paired_trim.fastq.gz
do
file2=${file1/_forward_paired_trim.fastq.gz/_reverse_paired_trim.fastq.gz}

fastqc ${file1}
fastqc ${file2}
done
