#!/bin/bash
#SBATCH -N 1
#SBATCH -p RM-shared
#SBATCH -t 48:00:00
#SBATCH --ntasks-per-node 32
#SBATCH -A ees240004p
#SBATCH --mail-type=ALL
#echo commands to stdout


module load anaconda3/2022.10
conda activate gtdbtk

gtdbtk identify --genome_dir /ocean/projects/ees240004p/hkittner/subsample_analysis/bins/bin_refinement_S4_04_L001only/metawrap_80_5_bins -x fa --out_dir /ocean/projects/ees240004p/hkittner/subsample_analysis/bins/gtdbtk_output/gtdbtk_identify_S4_04_L001only --cpus 32

gtdbtk align --identify_dir /ocean/projects/ees240004p/hkittner/subsample_analysis/bins/gtdbtk_output/gtdbtk_identify_S4_04_L001only --out_dir /ocean/projects/ees240004p/hkittner/subsample_analysis/bins/gtdbtk_output/gtdbtk_align_S4_04_L001only --cpus 32

gtdbtk classify --genome_dir /ocean/projects/ees240004p/hkittner/subsample_analysis/bins/bin_refinement_S4_04_L001only/metawrap_80_5_bins -x fa --align_dir /ocean/projects/ees240004p/hkittner/subsample_analysis/bins/gtdbtk_output/gtdbtk_align_S4_04_L001only --out_dir /ocean/projects/ees240004p/hkittner/subsample_analysis/bins/gtdbtk_output/gtdbtk_classify_S4_04_L001only --cpus 32
