#!/bin/bash
#SBATCH -N 1
#SBATCH -p RM-512
#SBATCH -t 72:00:00
#SBATCH --ntasks-per-node 128
#SBATCH -A ees240004p
#SBATCH --mail-type=ALL
#echo commands to stdout

module load anaconda3/2022.10

conda activate megahit

### Using preset for meta-large which uses options: '--min-count 2 --k-list 27,37,47,57,67,77,87' -- the preset didn't work so I input those parameters directly

megahit -t 128 -1 /ocean/projects/ees240004p/hkittner/trimmomatic_output/S4_04_L001_forward_paired_trim.fastq.gz -2 /ocean/projects/ees240004p/hkittner/trimmomatic_output/S4_04_L001_reverse_paired_trim.fastq.gz --min-count 2 --k-list 27,37,47,57,67,77,87 -o /ocean/projects/ees240004p/hkittner/subsample_megahit_meta_large_noEC_S4_04_L001
