#!/bin/bash
#SBATCH -N 1
#SBATCH -p RM-512
#SBATCH -t 72:00:00
#SBATCH --ntasks-per-node 128
#SBATCH -A ees240004p
#SBATCH --mail-type=ALL
#echo commands to stdout

module load anaconda3/2022.10

conda activate megahit

### Using preset for meta-large which uses options: '--min-count 2 --k-list 27,37,47,57,67,77,87'
### Using less threads because the original job failed because of an out of memory error


megahit -t 120 --continue -o /ocean/projects/ees240004p/hkittner/coassembly_analysis/assemblies/megahit_meta_large_S6_06
