#!/bin/bash
#SBATCH -N 1
#SBATCH -p RM-shared
#SBATCH -t 2:00:00
#SBATCH --ntasks-per-node 64
#SBATCH -A ees240004p
#SBATCH --mail-type=ALL
#echo commands to stdout

cd /ocean/projects/ees240004p/hkittner/subsample_analysis/bins/bin_refinement_S4_04_L001only/metawrap_80_5_bins

module load prodigal/2.6.3
for file1 in *.fa
do
    out=${file1%%.fa}
    prodigal -i ${file1} -o S4_04_subsample_${out}-coords.gbk -a S4_04_subsample_${out}-proteins.faa -d S4_04_subsample_${out}-nucleotides.fa
done
